### ISSUE TITLE
Can't render videos

### ISSUE THREAD

**Issue by Derus000002** [Adneths/fourier-drawer#13]
When i try to render a video this error happens: Preparing video
Traceback (most recent call last):
  File "E:\fourier-drawer\main.py", line 95, in <module>
    path, dims, frames = videoToPath(args.input, abs(args.density), args.points, dims, args.border)
  File "E:\fourier-drawer\libs\path.py", line 273, in videoToPath
    path = imageToPath(frame, base_density, N, False)
  File "E:\fourier-drawer\libs\path.py", line 216, in imageToPath
    return np.exp(1j*np.linspace(0,2*np.pi,N))
  File "<__array_function__ internals>", line 180, in linspace
  File "C:\Users\Utente\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\numpy\core\function_base.py", line 120, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

**Comment by Adneths** [comment]
Should be fixed under https://github.com/Adneths/fourier-drawer/tree/fix-main-13, see if you can verify it works.

**Comment by Derus000002** [comment]
> Should be fixed under https://github.com/Adneths/fourier-drawer/tree/fix-main-13, see if you can verify it works.

Thanks for the reply but i still can't render videos and it gives this error: Preparing video
Traceback (most recent call last):
  File "E:\fourier-drawer\main.py", line 95, in <module>
    path, dims, frames = videoToPath(args.input, abs(args.density), args.points, dims, args.border)
  File "E:\fourier-drawer\libs\path.py", line 274, in videoToPath
    path = imageToPath(frame, base_density, N, False)
  File "E:\fourier-drawer\libs\path.py", line 216, in imageToPath
    return np.zeros((N), dytpe=np.complex128)
TypeError: zeros() got an unexpected keyword argument 'dytpe'

**Comment by Adneths** [comment]
I changed the typo causing the syntax error. I've been doing the edits on my phone, so I couldn't try running the code.

**Comment by Derus000002** [comment]
> I changed the typo causing the syntax error. I've been doing the edits on my phone, so I couldn't try running the code.

Thanks a lot now it does render the video, but it draws just a mess of lines one on top of the other for some reason. Can you help with that?

**Comment by Adneths** [comment]
Can you show me the command you used as well as an image of what it looks like?

**Comment by Derus000002** [comment]
> Can you show me the command you used as well as an image of what it looks like?

i used this command: python main.py -i sample\ar.mp4 -v -o sample\ar -ss 2*pi --density 5 -dim 600x400 --show
![Screenshot 2024-07-02 150141](https://github.com/Adneths/fourier-drawer/assets/126360702/0853f77d-dfd5-43c1-bcea-ad63afe7267f)
this is a screenshot of the 6 seconds video it made

**Comment by Derus000002** [comment]
> Can you show me the command you used as well as an image of what it looks like?

I just need a recommended command for rendering videos if you have one (if my command was the error).

**Comment by Adneths** [comment]
The problem is that your timestep is the default timestep of 1/60 so it only computes 2\*pi\*60 samples of the animation. Try adding `-t 2*pi/${frames}/A -fpf A*F -fps F -tl 2*pi/${frames}` where `F` is the fps and `A` is some factor to control detail.

- `-t 2*pi/${frames}/A` allocates 2\*p\i*A samples for each video frame
- `-fpf A*F` make it draw 1 frame every A*F samples
- `-fps F` sets the output fps to F
- `-tl 2*pi/${frames}` limits the trail to only last 1 video frame

**Comment by Derus000002** [comment]
Thanks now it works correctly
